### ISSUE TITLE
Default values not being set on insert

### ISSUE THREAD

**Issue by juanbenitez** [apioo/fusio-adapter-sql#1]
Hello guys! 
I think i found a problem in the **Action/SqlActionAbstract.php** file, related to default value fields when inserting a new record, in particular, i'm using a datetime field that with a default value set to CURRENT_TIMESTAMP.

Use case:

Table
 - id integer
 - title varchar
 - created_at datetime default CURRENT_TIMESTAMP

My model
 - id
 - title

The problem: On insert, the 'created_at' field should use the default value (CURRENT_TIMESTAMP) but it was set to NULL.

Seems that the 'getData' method does not manage properly the default values, so when inserting a new record the field should be set to CURRENT_TIMESTAMP if the column evaluated is not part of the request... posible solution with comments:

inside the foreach:

```
if ($column->getAutoincrement()) {
                // in case the column is autoincrement we dont need it
                continue;
            }

            $value = null;
            if ($body->hasProperty($column->getName())) {

	        // field is in the request, set the value
                $value = $body->getProperty($column->getName()); 

            } elseif (!$validateNull) {
	        // field is not in the request, but we don't care null values in the request (but on insert this is TRUE)
                continue; 

            } elseif ($column->getDefault()) {
	        // my solution --> field is not in the request,
	 	// but if the column has a default value set we can continue to the next column
                continue; 
            } 
```

I tested it and it is working now in my installation, don't know if this could be helpfull, what do you think guys?

Setup details:
PHP 7.4 / Apache
Mysql 8.0.23-0ubuntu0.20.04.1 (Ubuntu)

**Comment by chriskapp** [comment]
Hi, yes you are correct, currently we dont handle default values and your changes look like a good idea, if you like you can submit a PR to commit those changes otherwise I can also commit them directly to the repo.

**Comment by juanbenitez** [comment]
Hi @chriskapp I sent a PR. 
Let me know if it is ok for you.
Thanks!
